project:
  type: book

book:
  title: The SocioEconomic Aspects of Stock Assessments Report
  subtitle: Recommendations for Increasing Assessment Accuracy and Improving Management Advice
  author:
    - name: Jane Doe
      affiliations:
        - name: University of XXX
          department: Department of YYY
    - name: Eva Nováková
      affiliations:
        - name: University of XXX
          department: Department of YYY
    - name: Matti Meikäläinen
      affiliations:
        - name: University of XXX
          department: Department of YYY
  chapters:
    - index.qmd
    - preface.qmd
    - text/tips.qmd
    - text/tables_figures.qmd
    - text/kable_flex.qmd
    - text/conclusion.qmd
    - references.qmd
    - text/appendix_tables.qmd

bibliography: references.bib

execute:
  echo: false

format:
  docx:
    toc: true
    reference-doc: template.docx
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
  pdf:
    documentclass: scrbook
    template-partials: ["partials/before-body.tex"]
    toc: true
    lof: true
    lot: true
    include-in-header: 
      text: |
        \newcommand*{\plogo}{\fbox{$\mathcal{PL}$}} % Generic dummy publisher logo
        \usepackage[utf8]{inputenc} % Required for inputting international characters
        \usepackage[T1]{fontenc} % Output font encoding for international characters
        \usepackage{hyphenat}
        \usepackage{authblk}
   

