project:
  type: book
  output-dir: docs
  output-file: "QmdReport"

book:
  title: An example report
  subtitle: The subtitle
#  cover-image: images/logo.png
#  image: images/logo.png
  downloads: [pdf, docx]
#  sharing: [twitter, facebook]
  author:
    - name: Jane Doe
      affiliations:
        - name: University of XXX
          department: Department of YYY
    - name: Eva Nováková
      affiliations:
        - name: University of XXX
          department: Department of YYY
    - name: Matti Meikäläinen
      affiliations:
        - name: University of XXX
          department: Department of YYY
  chapters:
    - index.qmd
#    - text/CRchum.qmd
    - text/ICSRFchinook.qmd
    - text/ICSRsthd.qmd   
    - text/ICUCchinook.qmd
    - text/ICUCsthd.qmd
    - text/LCchinook.qmd
#    - text/LCcoho.qmd    
    - text/LCsthd.qmd
#    - text/OCcoho.qmd     
#    - text/HCchum.qmd
    - text/UWchinook.qmd
    - text/UWsthd.qmd
    - text/conclusion.qmd
    - references.qmd

  site-url: https://rverse-tutorials.github.io/QmdReport/
  repo-url: https://github.com/RVerse-Tutorials/QmdReport
  repo-actions: [edit, source, issue]
  search: true

bibliography: [references.bib, SEDAR.bib]

execute:
  echo: false
  code-overflow: wrap

format:
  docx:
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
  pdf:
    documentclass: scrbook
    classoption: ["oneside"]
    template-partials: ["partials/before-body.tex"]
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    include-in-header: 
      - partials/inheader.tex


