project:
  type: book

book:
  title: "Quarto Report"
  chapters:
    - index.qmd
    - preface.qmd
    - text/tips.qmd
    - text/tables_figures.qmd
    - text/table_for_loop.qmd
    - text/kable_flex.qmd
    - text/conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  docx:
    toc: true
    reference-doc: template.docx
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt